### PR TITLE
Create CodingStandards

### PR DESCRIPTION
**Pull request by ModestosV**
Simple Coding Standards to ensure consistency among developers

### CODE REVIEW

**Review by mikebasdeo — CHANGES_REQUESTED** [review]
Can we also add a seperate coding standard for XML vs Java code? XML is used to define all the layout objects, and java is used to give each object functionality, so its nice to differentiate between the two using a separate coding standard. 

Optional: I like putting the name of the activity in front of the XML object name, for organization. But we don't have to enforce that.

 +XML objects. (lower case and underscores)
 +Good: main_activity_text_view
 +Good: main_activity_clear_button
 +Bad: mainButton
 +Bad: MainButton

**Comment by marcdragon123** [comment]
Looks good but changes mike suggested would be worth while

**Review by marcdragon123 — APPROVED** [review]

**Comment by ModestosV** [comment]
Small XML section added to file.

**Review by mikebasdeo — APPROVED** [review]

**Comment by mikebasdeo** [comment]
awesomeCodeStandards = view.findViewById(R.id.good_job)

**Pull request merged**
